version: "3.1"

services:
  coderr_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: franco_db
      MYSQL_ROOT_USER: root
      MYSQL_USER: franco
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret 